# SITE CONFIGURATION
title: Keep
rights: Zhou He
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://zhouhe018.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Zhou He
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Work', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Resume', link: '/contact'}

tagline: >
  Hi, I'm Zhou He - I'm a product designer in Nanjing, also a life-long learner.

hero_img: posts/texture1.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: zhouhe018@hotmail.com # email for form submission

twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  zhouhe018 # replace with your_github_username or comment to remove link from footer
instagram_username: vrane016 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: Zhou He # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
